import { Component, Inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-fetch-data',
  templateUrl: './fetch-data.component.html'
})
export class FetchDataComponent {
  public forecasts: WeatherForecast[];

  constructor(private http: HttpClient, @Inject('BASE_URL') private baseUrl: string) {
    http.get<WeatherForecast[]>(baseUrl + 'weatherforecast').subscribe(result => {
      this.forecasts = result;
    }, error => console.error(error));
  }

  downloadExcelFromCSV() {
    this.http.get(this.baseUrl + 'weatherforecast/download', { responseType: 'blob' }).subscribe(data => {
      // Filename autogenerated
      //const blob = new Blob([data], { type: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' });
      //const url = window.URL.createObjectURL(blob);
      //window.open(url);

      // For Fixed Filename
      var link = document.createElement('a');
      link.href = window.URL.createObjectURL(data);
      link.download = "data.xlsx";
      link.click();
    })
  }
}

interface WeatherForecast {
  date: string;
  temperatureC: number;
  temperatureF: number;
  summary: string;
}
